### ISSUE TITLE
Hooks do not support irregular calls to GetTargetArea

### ISSUE THREAD

**Issue by tos-x** [kartoFlane/ITB-ModUtils#16] opened 2023-04-20 12:17 UTC
As far as I can tell there are 2 irregular calls to `GetTargetArea()` in vanilla ItB; one from the Support_Repair's `GetSkillEffect` and one from Support_Wind's `GetTargetZone`. These two calls are made with a `nil` argument (in Support_Repair this is because `point` is undefined, likely a copy-paste error by the devs).

The `targetAreaBuildHook` and `secondTargetAreaBuildHook` have lines in them to call `Board:GetPawn(p)` where `p` is expected to be the point argument of the `GetTargetArea()`. `Board:GetPawn(nil)` will throw an error. This can be tested easily:

1. Install modloader and latest extensions. Ensure modApiExt is enabled.
2. Start a run, use console `weapon Support_Repair` to obtain the Repair Drop weapon and equip it to a mech.
3. Enter test mech scenario and attempt to fire the weapon; screen will go black, weapon will not work, and error.txt will have the following:
```
No matching overload found, candidates:
BoardPawn* GetPawn(Board&,int)
BoardPawn* GetPawn(Board&,Point,bool)
BoardPawn* GetPawn(Board&,Point)
```
Disabling modApiExt fixes the issue.

Need to have the hooks account for the possibility of the point input being nil, in some way that is easy for modders using the hooks to check.

Another random note, the AE mission with the exploding RST buildings has function `Trapped_Explode:GetTargetArea(p1,p2)` but p2 is never used. Still an irregular call to `GetTargetArea()`

**Comment by Lemonymous** [comment] 2023-04-22 16:54
Closing this issue, because #17 resolves the error caused by skill events.

If there are additional issues that are described here that have not been resolved, don't hesitate to open a new issue for it.

**Closed as completed by Lemonymous** 2023-04-22 16:54 UTC
